name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repo
        uses: actions/checkout@v2.3.4

      - name: Setup Java JDK
        uses: actions/setup-java@v2.1.0
        with:
          distribution: 'adopt'
          java-version: 8

      # https://github.com/actions/cache/blob/master/examples.md#java---gradle
      - name: Cache
        uses: actions/cache@v2.1.6
        id: cache
        with:
          path: |
            ~/.m2
            ~/.gradle/caches
            ~/.gradle/wrapper/
            ~/.android/build-cache
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # git update-index --chmod=+x gradlew
      - name: Build with Gradle
        run: ./gradlew clean build
